export const PERMISSIONS = Object.freeze({
  USERS_MANAGE: "users.manage",
  ROLES_MANAGE: "roles.manage",
  AUDIT_READ: "audit.read",
  PRODUCTS_READ: "products.read",
  PRODUCTS_MANAGE: "products.manage",
  WAREHOUSES_READ: "warehouses.read",
  WAREHOUSES_MANAGE: "warehouses.manage",
  SUPPLIERS_READ: "suppliers.read",
  SUPPLIERS_MANAGE: "suppliers.manage",
  CUSTOMERS_READ: "customers.read",
  CUSTOMERS_MANAGE: "customers.manage",
  QUOTATIONS_READ: "quotations.read",
  QUOTATIONS_MANAGE: "quotations.manage",
  SALES_ORDERS_READ: "sales_orders.read",
  SALES_ORDERS_CREATE: "sales_orders.create",
  SALES_ORDERS_UPDATE: "sales_orders.update",
  SALES_ORDERS_CONFIRM: "sales_orders.confirm",
  SALES_ORDERS_DELIVER: "sales_orders.deliver",
  INVOICES_READ: "invoices.read",
  INVOICES_CREATE: "invoices.create",
  INVOICES_CANCEL: "invoices.cancel",
  PAYMENTS_READ: "payments.read",
  PAYMENTS_CREATE: "payments.create",
  ACCOUNTS_READ: "accounts.read",
  ACCOUNTS_MANAGE: "accounts.manage",
  JOURNAL_ENTRIES_READ: "journal_entries.read",
  CUSTOMER_STATEMENTS_READ: "customer_statements.read",
  SUPPLIER_STATEMENTS_READ: "supplier_statements.read",
  PURCHASE_ORDERS_READ: "purchase_orders.read",
  PURCHASE_ORDERS_CREATE: "purchase_orders.create",
  PURCHASE_ORDERS_UPDATE: "purchase_orders.update",
  PURCHASE_ORDERS_APPROVE: "purchase_orders.approve",
  PURCHASE_ORDERS_CANCEL: "purchase_orders.cancel",
  GOODS_RECEIPTS_READ: "goods_receipts.read",
  GOODS_RECEIPTS_CREATE: "goods_receipts.create",
  INVENTORY_READ: "inventory.read",
  INVENTORY_ADJUST: "inventory.adjust",
  INVENTORY_TRANSFER: "inventory.transfer",
  INVENTORY_COUNT: "inventory.count",
  INVENTORY_COUNT_APPROVE: "inventory.count.approve",
  INVENTORY_LOW_STOCK_READ: "inventory.low_stock.read",
  REPORTS_PROFIT_READ: "reports.profit.read",
  REPORTS_TOP_PRODUCTS_READ: "reports.top_products.read",
  REPORTS_INVENTORY_VALUATION_READ: "reports.inventory_valuation.read",
  REPORTS_RECEIVABLES_READ: "reports.receivables.read",
  REPORTS_MONTHLY_SALES_READ: "reports.monthly_sales.read",
});

export function hasPermission(user, permission) {
  if (!permission) return true;
  return user?.permissions?.includes(permission) ?? false;
}
