export const arabicUi = {
  "Welcome back": "مرحباً بعودتك",
  "Sign in": "تسجيل الدخول",
  "Signing in...": "جارٍ تسجيل الدخول...",
  "Username or email": "اسم المستخدم أو البريد الإلكتروني",
  Password: "كلمة المرور",
  "Show password": "إظهار كلمة المرور",
  "Hide password": "إخفاء كلمة المرور",
  Dashboard: "لوحة التحكم",
  Overview: "نظرة عامة",
  Users: "المستخدمون",
  Products: "المنتجات",
  Categories: "التصنيفات",
  Warehouses: "المستودعات",
  Inventory: "المخزون",
  Reports: "التقارير",
  Settings: "الإعدادات",
  "Workspace overview": "نظرة عامة على مساحة العمل",
  Account: "الحساب",
  "Access level": "مستوى الوصول",
  Administrator: "مسؤول النظام",
  "Standard user": "مستخدم عادي",
  "Your access": "صلاحيات وصولك",
  "Roles and permissions": "الأدوار والصلاحيات",
  "Assigned roles": "الأدوار المعيّنة",
  "Available permissions": "الصلاحيات المتاحة",
  "No roles assigned": "لا توجد أدوار معيّنة",
  "Your account is ready. Use the navigation to access the areas available to you.":
    "حسابك جاهز. استخدم قائمة التنقل للوصول إلى الأقسام المتاحة لك.",
  "Access to each area is controlled by the roles assigned to your account.":
    "يتم التحكم بالوصول إلى كل قسم من خلال الأدوار المعيّنة لحسابك.",
  Active: "نشط",
  Inactive: "غير نشط",
  Optional: "اختياري",
  Action: "الإجراء",
  Actions: "الإجراءات",
  Previous: "السابق",
  Next: "التالي",
  Cancel: "إلغاء",
  Save: "حفظ",
  Close: "إغلاق",
  "Try again": "إعادة المحاولة",
  "Add user": "إضافة مستخدم",
  "Edit user": "تعديل المستخدم",
  "Create user": "إنشاء مستخدم",
  "Save changes": "حفظ التغييرات",
  "First name": "الاسم الأول",
  "Last name": "اسم العائلة",
  Email: "البريد الإلكتروني",
  Username: "اسم المستخدم",
  Role: "الدور",
  Status: "الحالة",
  "Search by name or email...": "البحث بالاسم أو البريد الإلكتروني...",
  "All statuses": "جميع الحالات",
  "Reset password": "إعادة تعيين كلمة المرور",
  "New password": "كلمة المرور الجديدة",
  "Change password": "تغيير كلمة المرور",
  "Deactivate account": "تعطيل الحساب",
  "Account deactivated": "تم تعطيل الحساب",
  "User added successfully": "تمت إضافة المستخدم بنجاح",
  "User updated successfully": "تم تحديث المستخدم بنجاح",
  "Password changed successfully": "تم تغيير كلمة المرور بنجاح",
  "Create a new account and assign its role in the system.":
    "أنشئ حساباً جديداً وحدد دوره في النظام.",
  "Update this account’s details and assigned roles.":
    "حدّث بيانات هذا الحساب والأدوار المعيّنة له.",
  "Roles & permissions": "الأدوار والصلاحيات",
  "Create role": "إنشاء دور",
  "Edit role": "تعديل الدور",
  "Save role": "حفظ الدور",
  "Role name": "اسم الدور",
  Description: "الوصف",
  Permissions: "الصلاحيات",
  "Deactivate role": "تعطيل الدور",
  "Create a role and define its initial permissions.":
    "أنشئ دوراً وحدد صلاحياته الأولية.",
  "Update the role details and choose its permissions.":
    "حدّث بيانات الدور واختر صلاحياته.",
  "Role created": "تم إنشاء الدور",
  "Role updated": "تم تحديث الدور",
  "Role deactivated": "تم تعطيل الدور",
  "Briefly describe this role": "اكتب وصفاً مختصراً لهذا الدور",
  "Audit logs": "سجل التدقيق",
  "Audit trail": "مسار التدقيق",
  "View details": "عرض التفاصيل",
  "System activity": "نشاط النظام",
  "Review security-sensitive actions and record changes.":
    "راجع الإجراءات الحساسة أمنياً والتغييرات على السجلات.",
  Filters: "عوامل التصفية",
  Apply: "تطبيق",
  Resource: "المورد",
  Record: "السجل",
  Date: "التاريخ",
  Details: "التفاصيل",
  System: "النظام",
  "Loading audit events...": "جارٍ تحميل أحداث التدقيق...",
  "Unable to load audit logs": "تعذر تحميل سجل التدقيق",
  "No events found": "لم يتم العثور على أحداث",
  "Try adjusting the current filters.": "جرّب تعديل عوامل التصفية الحالية.",
  User: "المستخدم",
  "Table / resource": "الجدول / المورد",
  "Record ID": "رقم السجل",
  "IP address": "عنوان IP",
  Timestamp: "الوقت",
  "From date": "من تاريخ",
  "To date": "إلى تاريخ",
  "Apply filters": "تطبيق الفلاتر",
  "Clear filters": "مسح الفلاتر",
  "Action, e.g. login": "الإجراء، مثل تسجيل الدخول",
  "Table, e.g. users": "الجدول، مثل المستخدمين",
  "Previous values": "القيم السابقة",
  "New values": "القيم الجديدة",
  "No values recorded": "لا توجد قيم مسجلة",
  "Product catalog": "دليل المنتجات",
  "Add product": "إضافة منتج",
  "Edit product": "تعديل المنتج",
  "Import CSV": "استيراد CSV",
  "Importing...": "جارٍ الاستيراد...",
  "Catalog management": "إدارة الدليل",
  "Keep product details, pricing, and categories organized in one place.":
    "حافظ على تنظيم بيانات المنتجات والأسعار والتصنيفات في مكان واحد.",
  "Products found": "المنتجات الموجودة",
  "Active categories": "التصنيفات النشطة",
  "Priced products on this page": "المنتجات المسعّرة في هذه الصفحة",
  "Organize products into clear catalog groups":
    "نظّم المنتجات ضمن مجموعات واضحة",
  "No barcode": "بدون باركود",
  Uncategorized: "غير مصنّف",
  "Low-stock threshold": "حد تنبيه نقص المخزون",
  "Unable to load data": "تعذر تحميل البيانات",
  "Deactivate product": "تعطيل المنتج",
  "Deactivate category": "تعطيل التصنيف",
  "Product name": "اسم المنتج",
  SKU: "رمز SKU",
  Barcode: "الباركود",
  Category: "التصنيف",
  "Cost price": "سعر التكلفة",
  "Sale price": "سعر البيع",
  "Low-stock alert threshold": "حد تنبيه نقص المخزون",
  "Create the catalog record only. Stock is added later to a selected warehouse through inventory receiving or adjustment.":
    "سيُنشأ سجل المنتج فقط. تُضاف الكمية لاحقًا إلى مستودع محدد من خلال الاستلام أو تعديل المخزون.",
  "This is an alert threshold, not the current quantity. Whole units only.":
    "هذا حد للتنبيه وليس الكمية الحالية. أدخل وحدات صحيحة فقط.",
  "Search name, SKU, or barcode...": "البحث بالاسم أو SKU أو الباركود...",
  "All categories": "جميع التصنيفات",
  "Add a product to your catalog with its pricing and stock settings.":
    "أضف منتجاً مع الأسعار وإعدادات المخزون.",
  "Update product identity, pricing, and stock settings.":
    "حدّث بيانات المنتج وأسعاره وإعدادات المخزون.",
  "Product added successfully": "تمت إضافة المنتج بنجاح",
  "Product updated successfully": "تم تحديث المنتج بنجاح",
  "Product deactivated": "تم تعطيل المنتج",
  "No matching products": "لا توجد منتجات مطابقة",
  "Change your filters or add your first product.":
    "غيّر عوامل التصفية أو أضف أول منتج.",
  "Loading products...": "جارٍ تحميل المنتجات...",
  "Add category": "إضافة تصنيف",
  "Edit category": "تعديل التصنيف",
  "Category name": "اسم التصنيف",
  "Parent category": "التصنيف الأب",
  "No parent category": "بدون تصنيف أب",
  "Top-level category": "تصنيف رئيسي",
  "No categories yet": "لا توجد تصنيفات بعد",
  "Loading categories...": "جارٍ تحميل التصنيفات...",
  "Add a category to organize the product catalog.":
    "أضف تصنيفاً لتنظيم دليل المنتجات.",
  "Optional. Select a parent only when this is a subcategory.":
    "اختياري. اختر تصنيفاً أباً فقط للتصنيفات الفرعية.",
  "Category added successfully": "تمت إضافة التصنيف بنجاح",
  "Category updated successfully": "تم تحديث التصنيف بنجاح",
  "Category deactivated": "تم تعطيل التصنيف",
  "Location management": "إدارة المواقع",
  "Add warehouse": "إضافة مستودع",
  "Edit warehouse": "تعديل المستودع",
  "Warehouse code": "رمز المستودع",
  "Warehouse name": "اسم المستودع",
  Address: "العنوان",
  Location: "الموقع",
  "Search code, name, or address...": "البحث بالرمز أو الاسم أو العنوان...",
  "Active locations": "المستودعات النشطة",
  "Inactive locations": "المستودعات غير النشطة",
  "Create a warehouse for inventory and business operations.":
    "أنشئ مستودعاً لعمليات المخزون والأعمال.",
  "Update the warehouse identity and location.": "حدّث بيانات المستودع وموقعه.",
  "Optional warehouse location": "موقع المستودع اختياري",
  "No address provided": "لم يتم إدخال عنوان",
  "Warehouse added successfully": "تمت إضافة المستودع بنجاح",
  "Warehouse updated successfully": "تم تحديث المستودع بنجاح",
  "Warehouse deactivated": "تم تعطيل المستودع",
  "No matching warehouses": "لا توجد مستودعات مطابقة",
  "Loading warehouses...": "جارٍ تحميل المستودعات...",
  "Unable to load warehouses": "تعذر تحميل المستودعات",
  "Inventory control": "التحكم بالمخزون",
  "Stock operations": "عمليات المخزون",
  "Adjust stock": "تعديل المخزون",
  "Transfer stock": "نقل المخزون",
  "Stock overview": "نظرة عامة على المخزون",
  "Movement history": "سجل الحركات",
  "Low stock": "المخزون المنخفض",
  "Physical counts": "الجرد الفعلي",
  "Stock records": "سجلات المخزون",
  "Total stock quantity": "إجمالي كمية المخزون",
  "Active warehouses": "المستودعات النشطة",
  "Low-stock products": "منتجات منخفضة المخزون",
  "Sum of quantities in the current filtered results":
    "مجموع الكميات في نتائج التصفية الحالية",
  "Product and location pairs": "المنتجات ومواقعها",
  "Across all filtered locations": "عبر جميع المواقع المفلترة",
  "Available inventory locations": "مواقع المخزون المتاحة",
  "Based on total product stock": "بناءً على إجمالي مخزون المنتج",
  "Stock by location": "المخزون حسب الموقع",
  "Each row represents one product stored in one warehouse.":
    "يمثل كل صف منتجاً مخزناً في مستودع واحد.",
  "Search SKU or product name...": "البحث بـSKU أو اسم المنتج...",
  "All warehouses": "جميع المستودعات",
  Product: "المنتج",
  Warehouse: "المستودع",
  "Quantity at location": "الكمية في الموقع",
  Updated: "آخر تحديث",
  Adjust: "تعديل",
  "Loading stock...": "جارٍ تحميل المخزون...",
  "Unable to load stock": "تعذر تحميل المخزون",
  "No stock matches these filters": "لا يوجد مخزون مطابق لهذه الفلاتر",
  "An auditable timeline of every quantity change.":
    "سجل قابل للتدقيق لكل تغيير في الكمية.",
  "All products": "جميع المنتجات",
  "All movement types": "جميع أنواع الحركات",
  "Stock in": "إدخال مخزون",
  "Stock out": "إخراج مخزون",
  Adjustment: "تعديل",
  "Loading movements...": "جارٍ تحميل الحركات...",
  "Unable to load movements": "تعذر تحميل الحركات",
  "No movements match these filters": "لا توجد حركات مطابقة لهذه الفلاتر",
  "Low-stock alerts": "تنبيهات انخفاض المخزون",
  "Checking stock levels...": "جارٍ فحص مستويات المخزون...",
  "Unable to load low-stock alerts": "تعذر تحميل تنبيهات المخزون",
  "All products are above their minimum stock level":
    "جميع المنتجات أعلى من الحد الأدنى للمخزون",
  available: "متوفر",
  minimum: "الحد الأدنى",
  short: "النقص",
  "Manual stock adjustment": "تعديل يدوي للمخزون",
  "Quantity change (units)": "تغيير الكمية (وحدات)",
  Reason: "السبب",
  "Save adjustment": "حفظ التعديل",
  "Select product": "اختر المنتج",
  "Select warehouse": "اختر المستودع",
  "Enter 9 to add or -9 to remove": "أدخل 9 للإضافة أو -9 للإزالة",
  "Example: Physical count correction": "مثال: تصحيح نتيجة الجرد",
  "Stock adjustment saved": "تم حفظ تعديل المخزون",
  "Source warehouse": "المستودع المصدر",
  "Destination warehouse": "المستودع الوجهة",
  "Select source": "اختر المصدر",
  "Select destination": "اختر الوجهة",
  "Quantity (units)": "الكمية (وحدات)",
  "Transfer preview": "معاينة النقل",
  "Confirm transfer": "تأكيد النقل",
  "Current stock:": "المخزون الحالي:",
  "Available:": "المتاح:",
  "Enter whole units": "أدخل وحدات كاملة",
  "Quantity exceeds available stock.": "الكمية تتجاوز المخزون المتاح.",
  "Physical stock counts": "عمليات الجرد الفعلي",
  "New count": "جرد جديد",
  "Pending approval": "بانتظار الاعتماد",
  "Approved counts": "عمليات الجرد المعتمدة",
  "All counts": "جميع عمليات الجرد",
  Expected: "المتوقع",
  Counted: "المعدود",
  Variance: "الفرق",
  Approve: "اعتماد",
  "Loading physical counts...": "جارٍ تحميل عمليات الجرد...",
  "Unable to load physical counts": "تعذر تحميل عمليات الجرد",
  "No physical counts match this status": "لا توجد عمليات جرد بهذه الحالة",
  "Record physical count": "تسجيل جرد فعلي",
  "Counted quantity (units)": "الكمية المعدودة (وحدات)",
  "System quantity": "كمية النظام",
  "Count notes": "ملاحظات الجرد",
  "Submit count": "إرسال الجرد",
  "Physical count submitted for approval": "تم إرسال الجرد للاعتماد",
  "A different authorized user must approve this count.":
    "يجب أن يعتمد هذا الجرد مستخدم مخوّل آخر.",
  "Administrator workspace": "مساحة مسؤول النظام",
  "One clear view of the business": "نظرة واضحة واحدة على الأعمال",
  "Monitor ownership and follow the operational journey without opening every module.":
    "راقب المسؤوليات وتابع مسار العمليات دون فتح كل قسم.",
  "Access control": "التحكم بالصلاحيات",
  "Business roles": "أدوار الأعمال",
  "Needs attention": "بحاجة إلى متابعة",
  "People with system access": "الأشخاص الذين يملكون صلاحية دخول النظام",
  "Defined operational ownership": "مسؤوليات تشغيلية محددة",
  "Products currently below threshold": "منتجات أقل من حد التنبيه حالياً",
  "Process tracking": "تتبع العمليات",
  "Product-to-stock journey": "مسار المنتج إلى المخزون",
  "This shows implementation readiness now. Live purchase-order tracking starts when the Purchase Orders module is built.":
    "يعرض هذا جاهزية مراحل النظام حالياً. يبدأ تتبع طلبات الشراء الفعلية عند بناء قسم طلبات الشراء.",
  "Procurement flow": "مسار المشتريات",
  Supplier: "المورد",
  "Catalog record created": "سجل المنتج جاهز",
  "Approved partner selected": "تم اختيار مورد معتمد",
  "Open products": "فتح المنتجات",
  "Open suppliers": "فتح الموردين",
  "Purchase order": "طلب الشراء",
  "Next module to build": "القسم التالي للبناء",
  "Manager approval": "اعتماد المدير",
  "Planned workflow": "مرحلة مخطط لها",
  "Goods receipt": "استلام البضاعة",
  "Warehouse stock": "مخزون المستودع",
  "Inventory foundation ready": "أساس المخزون جاهز",
  "Open inventory": "فتح المخزون",
  "Role ownership": "مسؤوليات الأدوار",
  "Who controls each operation?": "من المسؤول عن كل عملية؟",
  Open: "فتح",
  "Next to build": "التالي للبناء",
  "Manage team": "إدارة الفريق",
  "Active users": "المستخدمون النشطون",
  "Manage permissions": "إدارة الصلاحيات",
  "Purchasing Officer": "موظف المشتريات",
  "Sales Officer": "موظف المبيعات",
  "Warehouse Keeper": "أمين المستودع",
  Accountant: "المحاسب",
  Manager: "المدير",
  "Products and categories": "المنتجات والتصنيفات",
  Suppliers: "الموردون",
  "Purchase orders": "طلبات الشراء",
  Customers: "العملاء",
  Quotations: "عروض الأسعار",
  "Sales orders": "طلبات البيع",
  "Goods receipts": "سندات الاستلام",
  Transfers: "عمليات النقل",
  "Physical counts": "الجرد الفعلي",
  "Chart of accounts": "دليل الحسابات",
  Invoices: "الفواتير",
  "Payments and reports": "الدفعات والتقارير",
  "Purchase approvals": "اعتماد المشتريات",
  "Count approvals": "اعتماد الجرد",
  "Management reports": "تقارير الإدارة",
  Planned: "مخطط",
  "My workspace": "مساحة عملي",
  "Your workspace contains the daily operations assigned to your role.":
    "تحتوي مساحة عملك على العمليات اليومية المعيّنة لدورك.",
  "Procurement network": "شبكة المشتريات",
  "Maintain the approved companies your purchasing team can order from.":
    "أدر الشركات المعتمدة التي يمكن لفريق المشتريات الطلب منها.",
  "Add supplier": "إضافة مورد",
  "Edit supplier": "تعديل المورد",
  "Deactivate supplier": "تعطيل المورد",
  "Total suppliers": "إجمالي الموردين",
  "Active partners": "الشركاء النشطون",
  "Current results": "النتائج الحالية",
  "Inactive suppliers": "الموردون غير النشطين",
  "All supplier records": "جميع سجلات الموردين",
  "Available for purchasing": "متاحون للشراء",
  "Match the selected filters": "تطابق عوامل التصفية المحددة",
  "Commercial terms recorded": "شروط تجارية مسجلة",
  "Retained for history": "محفوظون للسجل التاريخي",
  "Supplier directory": "دليل الموردين",
  "Approved business partners": "شركاء الأعمال المعتمدون",
  "Search name, email, phone, or terms...":
    "البحث بالاسم أو البريد أو الهاتف أو شروط الدفع...",
  "Active suppliers": "الموردون النشطون",
  "Loading suppliers...": "جارٍ تحميل الموردين...",
  "Unable to load suppliers": "تعذر تحميل الموردين",
  "No matching suppliers": "لا يوجد موردون مطابقون",
  "Change the filters or create your first supplier.":
    "غيّر عوامل التصفية أو أضف أول مورد.",
  "Supplier name": "اسم المورد",
  "Email address": "البريد الإلكتروني",
  "Phone number": "رقم الهاتف",
  "Credit terms": "شروط الدفع",
  "No phone provided": "لا يوجد رقم هاتف",
  "Not specified": "غير محدد",
  "Create an approved supplier record for future purchase orders.":
    "أنشئ سجل مورد معتمد لطلبات الشراء المستقبلية.",
  "Update supplier contact and commercial terms.":
    "حدّث بيانات التواصل والشروط التجارية للمورد.",
  "Example: Net 30": "مثال: الدفع خلال 30 يوماً",
  "Optional payment agreement, such as Net 15, Net 30, or payment on delivery.":
    "اتفاق دفع اختياري، مثل الدفع خلال 15 أو 30 يوماً أو عند التسليم.",
  "Supplier added successfully": "تمت إضافة المورد بنجاح",
  "Supplier updated successfully": "تم تحديث المورد بنجاح",
  "Supplier deactivated": "تم تعطيل المورد",
  "Procurement control": "التحكم بالمشتريات",
  "Move approved supplier demand from draft to verified warehouse stock.":
    "انقل طلبات المورد المعتمدة من المسودة إلى مخزون مستودع موثّق.",
  "Create order": "إنشاء طلب",
  "All orders": "جميع الطلبات",
  "Complete procurement record": "سجل المشتريات الكامل",
  "Awaiting decision": "بانتظار القرار",
  "Pending manager approval": "بانتظار اعتماد المدير",
  "Ready to receive": "جاهز للاستلام",
  "Approved supplier deliveries": "توريدات الموردين المعتمدة",
  Received: "تم الاستلام",
  "Posted to inventory": "تم ترحيله إلى المخزون",
  "Order workspace": "مساحة الطلبات",
  "Procurement pipeline": "مسار المشتريات",
  "Search order number or supplier...": "ابحث برقم الطلب أو المورد...",
  "All suppliers": "جميع الموردين",
  Draft: "مسودة",
  Approved: "معتمد",
  Rejected: "مرفوض",
  Cancelled: "ملغي",
  "Loading purchase orders...": "جارٍ تحميل طلبات الشراء...",
  "Unable to load purchase orders": "تعذر تحميل طلبات الشراء",
  "No purchase orders yet": "لا توجد طلبات شراء بعد",
  "Create the first draft without entering supplier or product IDs manually.":
    "أنشئ أول مسودة دون إدخال أرقام المورد أو المنتجات يدوياً.",
  "Create first order": "إنشاء أول طلب",
  Edit: "تعديل",
  Submit: "إرسال",
  Reject: "رفض",
  Receive: "استلام",
  "Order total": "إجمالي الطلب",
  "Create purchase order": "إنشاء طلب شراء",
  "Edit purchase order": "تعديل طلب الشراء",
  "Build a draft order from active suppliers and catalog products. Stock is not changed until goods are received.":
    "أنشئ مسودة من الموردين والمنتجات النشطة. لا يتغير المخزون حتى استلام البضاعة.",
  "Update the supplier and ordered items while this order is still a draft.":
    "حدّث المورد والمنتجات المطلوبة ما دام الطلب مسودة.",
  "Select supplier": "اختر المورد",
  "Terms not specified": "الشروط غير محددة",
  "Internal notes": "ملاحظات داخلية",
  "Example: Monthly replenishment": "مثال: التوريد الشهري",
  "Order items": "بنود الطلب",
  "Whole units and agreed supplier cost":
    "وحدات صحيحة وتكلفة المورد المتفق عليها",
  "Add line": "إضافة بند",
  Quantity: "الكمية",
  "Unit cost": "تكلفة الوحدة",
  "Line total": "إجمالي البند",
  "This saves a draft only. Submit it when it is ready for manager approval.":
    "سيتم حفظ مسودة فقط. أرسلها عندما تصبح جاهزة لاعتماد المدير.",
  "Save draft": "حفظ المسودة",
  "Create draft": "إنشاء المسودة",
  "Purchase order created": "تم إنشاء طلب الشراء",
  "Purchase order updated": "تم تحديث طلب الشراء",
  "Purchase order submitted for approval": "تم إرسال طلب الشراء للاعتماد",
  "Purchase order approved": "تم اعتماد طلب الشراء",
  "Purchase order rejected": "تم رفض طلب الشراء",
  "Purchase order cancelled": "تم إلغاء طلب الشراء",
  "Goods received and inventory updated": "تم استلام البضاعة وتحديث المخزون",
  "Reject purchase order": "رفض طلب الشراء",
  "Cancel purchase order": "إلغاء طلب الشراء",
  "Reject order": "رفض الطلب",
  "Cancel order": "إلغاء الطلب",
  "Receive purchase order": "استلام طلب الشراء",
  "Receiving warehouse": "مستودع الاستلام",
  "Receipt notes": "ملاحظات الاستلام",
  "Example: Delivery checked and received": "مثال: تم فحص التوريد واستلامه",
  "Inventory will update immediately": "سيتم تحديث المخزون فوراً",
  "Confirm receipt": "تأكيد الاستلام",
  "Supplier commitment, approval trail, and receiving result in one record.":
    "التزام المورد ومسار الاعتماد ونتيجة الاستلام في سجل واحد.",
  Created: "تم الإنشاء",
  "Draft created": "تم إنشاء المسودة",
  Submitted: "تم الإرسال",
  "Manager decision": "قرار المدير",
  "Goods received": "تم استلام البضاعة",
  "Waiting for purchasing": "بانتظار المشتريات",
  "Waiting for approval": "بانتظار الاعتماد",
  "Waiting for delivery": "بانتظار التوريد",
  "Rejection reason": "سبب الرفض",
  "Cancellation reason": "سبب الإلغاء",
  "Procurement workflow ready": "مسار المشتريات جاهز",
  "Controlled approval ready": "الاعتماد المنضبط جاهز",
  "Warehouse receiving ready": "استلام المستودع جاهز",
  "Open purchase orders": "فتح طلبات الشراء",
  "The procurement workflow is live from supplier order through approval, receiving, and warehouse stock.":
    "مسار المشتريات يعمل من طلب المورد مروراً بالاعتماد والاستلام وحتى مخزون المستودع.",
  "Sales relationships": "علاقات المبيعات",
  "Customer directory": "دليل العملاء",
  "One reliable customer record for quotations, orders, invoices, and statements.":
    "سجل عميل موحد لعروض الأسعار والطلبات والفواتير وكشوف الحساب.",
  "Add customer": "إضافة عميل",
  "Edit customer": "تعديل العميل",
  "Deactivate customer": "تعطيل العميل",
  "Total customers": "إجمالي العملاء",
  "Complete customer base": "قاعدة العملاء الكاملة",
  "Active customers": "العملاء النشطون",
  "Available for new sales": "متاحون للمبيعات الجديدة",
  "Covered cities": "المدن المغطاة",
  "Customer market reach": "انتشار سوق العملاء",
  "Matching credit": "الحد الائتماني المطابق",
  "Current page credit limits": "حدود الائتمان في الصفحة الحالية",
  "Customer master data": "البيانات الرئيسية للعملاء",
  "Accounts and contacts": "الحسابات وجهات الاتصال",
  "Search code, name, contact, phone, or tax number...":
    "ابحث بالرمز أو الاسم أو جهة الاتصال أو الهاتف أو الرقم الضريبي...",
  "All cities": "جميع المدن",
  "Inactive customers": "العملاء غير النشطين",
  "Loading customers...": "جارٍ تحميل العملاء...",
  "Unable to load customers": "تعذر تحميل العملاء",
  "No matching customers": "لا يوجد عملاء مطابقون",
  "Add the first customer or change the current filters.":
    "أضف أول عميل أو غيّر عوامل التصفية الحالية.",
  "Add first customer": "إضافة أول عميل",
  Customer: "العميل",
  "Primary contact": "جهة الاتصال الرئيسية",
  Location: "الموقع",
  "Credit limit": "الحد الائتماني",
  Status: "الحالة",
  "Customer name": "اسم العميل",
  "Contact person": "اسم جهة الاتصال",
  Address: "العنوان",
  City: "المدينة",
  "Tax number": "الرقم الضريبي",
  "Credit limit (JOD)": "الحد الائتماني (دينار)",
  "Keep commercial and contact information ready for quotations and sales orders.":
    "احتفظ بالبيانات التجارية وبيانات الاتصال جاهزة لعروض الأسعار وطلبات البيع.",
  "Maximum approved credit for future sales. Use zero for cash-only customers.":
    "أقصى ائتمان معتمد للمبيعات المستقبلية. استخدم صفراً لعملاء الدفع النقدي.",
  "Customer updated successfully": "تم تحديث العميل بنجاح",
  "Customer added successfully": "تمت إضافة العميل بنجاح",
  "Customer deactivated": "تم تعطيل العميل",
  "No contact assigned": "لم تُحدد جهة اتصال",
  "No contact details": "لا توجد بيانات اتصال",
  "No address provided": "لا يوجد عنوان",
  "Approved ceiling": "السقف المعتمد",
  "Sales pipeline": "مسار المبيعات",
  Quotations: "عروض الأسعار",
  "Build clear offers, capture customer decisions, and prepare accepted demand for sales orders.":
    "أنشئ عروضاً واضحة وسجّل قرارات العملاء وجهّز الطلبات المقبولة لطلبات البيع.",
  "Create quotation": "إنشاء عرض سعر",
  "Edit quotation": "تعديل عرض السعر",
  "Matching quotations": "عروض الأسعار المطابقة",
  "Sales orders": "طلبات البيع",
  "Order fulfillment": "تنفيذ الطلبات",
  "Turn accepted offers into controlled warehouse deliveries with a complete inventory trail.":
    "حوّل العروض المقبولة إلى عمليات تسليم مستودعية مضبوطة مع سجل مخزون كامل.",
  "Matching orders": "الطلبات المطابقة",
  "Current register results": "نتائج السجل الحالية",
  "Ready to deliver": "جاهزة للتسليم",
  "Confirmed, stock unchanged": "مؤكدة دون تغيير المخزون",
  "Completed deliveries": "عمليات التسليم المكتملة",
  "Inventory already deducted": "تم خصم المخزون",
  "Fulfillment register": "سجل التنفيذ",
  "Customer orders": "طلبات العملاء",
  "Search order number or customer...": "ابحث برقم الطلب أو العميل...",
  "All statuses": "جميع الحالات",
  Draft: "مسودة",
  Delivered: "تم التسليم",
  Cancelled: "ملغي",
  "Unable to load sales orders": "تعذر تحميل طلبات البيع",
  "No sales orders yet": "لا توجد طلبات بيع بعد",
  "Accept a quotation, then convert it to a sales order.":
    "اقبل عرض سعر ثم حوّله إلى طلب بيع.",
  "Order total": "إجمالي الطلب",
  Details: "التفاصيل",
  "Confirm order": "تأكيد الطلب",
  "Deliver order": "تسليم الطلب",
  "Cancel sales order": "إلغاء طلب البيع",
  "Cancel order": "إلغاء الطلب",
  "Keep order": "الاحتفاظ بالطلب",
  "Sales order confirmed": "تم تأكيد طلب البيع",
  "Sales order cancelled": "تم إلغاء طلب البيع",
  "Sales order created": "تم إنشاء طلب البيع",
  "From quotation": "من عرض السعر",
  "Order created": "تم إنشاء الطلب",
  Confirmed: "مؤكد",
  "Warehouse delivery": "تسليم المستودع",
  "Not completed": "غير مكتمل",
  "Cancellation reason": "سبب الإلغاء",
  "Select one warehouse that can fulfill every line. Stock is deducted only after this action.":
    "اختر مستودعاً واحداً يستطيع توفير جميع البنود. يُخصم المخزون فقط بعد هذا الإجراء.",
  Ready: "جاهز",
  "Insufficient stock": "مخزون غير كافٍ",
  "Unable to check inventory": "تعذر التحقق من المخزون",
  "Delivery notes (optional)": "ملاحظات التسليم (اختياري)",
  "Deliver and deduct stock": "التسليم وخصم المخزون",
  "Send to customer": "إرسال للعميل",
  "Record rejection": "تسجيل الرفض",
  "Record acceptance": "تسجيل القبول",
  "Convert to sales order": "تحويل إلى طلب بيع",
  Converted: "تم التحويل",
  "Current workspace results": "نتائج مساحة العمل الحالية",
  "Awaiting customer": "بانتظار العميل",
  "Sent and awaiting decision": "أُرسلت وبانتظار القرار",
  "Accepted offers": "العروض المقبولة",
  "Ready for sales order": "جاهزة لطلب البيع",
  "Commercial offers": "العروض التجارية",
  "Quotation register": "سجل عروض الأسعار",
  "Search quotation number or customer...": "ابحث برقم عرض السعر أو العميل...",
  "No quotations yet": "لا توجد عروض أسعار بعد",
  "Create a draft offer for one of your active customers.":
    "أنشئ مسودة عرض لأحد عملائك النشطين.",
  "Unable to load quotations": "تعذر تحميل عروض الأسعار",
  Sent: "مُرسل",
  Accepted: "مقبول",
  Expired: "منتهي",
  Accept: "قبول",
  "Prepare a commercial offer using active customers and catalog products.":
    "جهّز عرضاً تجارياً باستخدام العملاء والمنتجات النشطة.",
  "Select customer": "اختر العميل",
  "Valid until": "صالح لغاية",
  "Quoted products": "المنتجات المعروضة",
  "Whole units and customer-facing prices": "وحدات صحيحة وأسعار مقدمة للعميل",
  "Whole units, customer-facing prices, and line discounts":
    "وحدات صحيحة وأسعار مقدمة للعميل وخصم لكل بند",
  "Unit price": "سعر الوحدة",
  "Line discount %": "خصم البند %",
  "Additional quotation discount %": "خصم إضافي على العرض %",
  "All discounts": "جميع الخصومات",
  "Discount %": "الخصم %",
  "Tax %": "الضريبة %",
  Notes: "ملاحظات",
  "Delivery, payment, or warranty terms": "شروط التسليم أو الدفع أو الضمان",
  Subtotal: "المجموع الفرعي",
  Discount: "الخصم",
  Tax: "الضريبة",
  Total: "الإجمالي",
  "Quotation updated": "تم تحديث عرض السعر",
  "Quotation created": "تم إنشاء عرض السعر",
  "Total offer": "إجمالي العرض",
  "Reject quotation": "رفض عرض السعر",
  "Record why the customer rejected": "سجّل سبب رفض العميل",
  "Commercial offer for": "عرض تجاري للعميل",
  "Product lines": "بنود المنتجات",
  "Rejection reason": "سبب الرفض",
  "Create draft": "إنشاء المسودة",
  "Mark expired": "تعليم كمنتهي",
  "Select the fulfillment warehouse. Confirmation checks every stock line and the customer credit limit without deducting inventory.":
    "اختر مستودع التنفيذ. سيتحقق التأكيد من مخزون جميع البنود والحد الائتماني للعميل دون خصم المخزون.",
  "Stock will be deducted from": "سيُخصم المخزون من",
  "the warehouse selected at confirmation": "المستودع المحدد عند التأكيد",
  "Quotation workspace": "مساحة عروض الأسعار",
  "Invoices & payments": "الفواتير والمدفوعات",
  "Accounts receivable": "حسابات العملاء المدينة",
  "Control every customer balance from delivered order to final settlement.":
    "تحكم برصيد كل عميل من الطلب المسلّم حتى السداد النهائي.",
  "Open documents": "المستندات المفتوحة",
  "Generate invoice": "إنشاء فاتورة",
  "Matching invoices": "الفواتير المطابقة",
  "Current register results": "نتائج السجل الحالية",
  "Awaiting payment": "بانتظار الدفع",
  "Issued with no payment": "صادرة دون دفعات",
  "Partially paid": "مدفوعة جزئياً",
  "Balance still outstanding": "لا يزال هناك رصيد مستحق",
  Overdue: "متأخرة",
  "Past due and unpaid": "تجاوزت الاستحقاق ولم تُدفع",
  "Customer finance": "مالية العملاء",
  "Invoice register": "سجل الفواتير",
  "Search invoice number or customer...": "ابحث برقم الفاتورة أو العميل...",
  "Overdue only": "المتأخرة فقط",
  "Unable to load invoices": "تعذر تحميل الفواتير",
  "No invoices found": "لم يتم العثور على فواتير",
  "Generate an invoice after a Sales Order has been delivered.":
    "أنشئ فاتورة بعد تسليم طلب البيع.",
  "Invoice total": "إجمالي الفاتورة",
  "Balance due": "الرصيد المستحق",
  "Record payment": "تسجيل دفعة",
  "Delivered Sales Order": "طلب البيع المسلّم",
  "Select an order...": "اختر طلباً...",
  "Due date (optional)": "تاريخ الاستحقاق (اختياري)",
  "Leave empty to use 30 days after delivery.":
    "اتركه فارغاً لاعتماد 30 يوماً بعد التسليم.",
  "Create draft invoice": "إنشاء مسودة فاتورة",
  "No delivered orders are waiting for an invoice.":
    "لا توجد طلبات مسلّمة بانتظار الفوترة.",
  "Record customer payment": "تسجيل دفعة عميل",
  "Amount (JOD)": "المبلغ (دينار)",
  "Payment date": "تاريخ الدفع",
  "Payment method": "طريقة الدفع",
  Cash: "نقداً",
  "Bank transfer": "تحويل بنكي",
  Card: "بطاقة",
  Cheque: "شيك",
  "Reference (optional)": "المرجع (اختياري)",
  "Post payment": "ترحيل الدفعة",
  "Customer invoice": "فاتورة العميل",
  "Bill to": "فاتورة إلى",
  "Issue date": "تاريخ الإصدار",
  "Payment history": "سجل المدفوعات",
  "Posted receipts and reversals": "الإيصالات المرحلة والعمليات المعكوسة",
  "No payments recorded.": "لا توجد دفعات مسجلة.",
  "Print invoice": "طباعة الفاتورة",
  Reverse: "عكس",
  "Reverse payment": "عكس الدفعة",
  "Keep record": "الاحتفاظ بالسجل",
  "Invoice issued": "تم إصدار الفاتورة",
  "Invoice cancelled": "تم إلغاء الفاتورة",
  "Invoice generated as draft": "تم إنشاء الفاتورة كمسودة",
  "Payment posted": "تم ترحيل الدفعة",
  "Payment reversed": "تم عكس الدفعة",
  Issued: "صادرة",
  Paid: "مدفوعة",
  Receivables: "الذمم المدينة",
  "Overdue invoice": "فاتورة متأخرة",
};

const patterns = [
  [/^Welcome, (.+)$/, "مرحباً، $1"],
  [/^User #(\d+)$/, "المستخدم رقم $1"],
  [/^Page (\d+) of (\d+)$/, "الصفحة $1 من $2"],
  [/^Page (\d+)$/, "الصفحة $1"],
  [/^(\d+) selected$/, "تم اختيار $1"],
  [/^Added (.+)$/, "أُضيف في $1"],
  [/^Recorded (.+)$/, "سُجل في $1"],
  [/^(\d+) locations?$/, "$1 مستودع"],
  [/^(\d+) matching products?$/, "$1 منتج مطابق"],
  [
    /^(\d+) products match the current filters$/,
    "$1 منتج مطابق لعوامل التصفية الحالية",
  ],
  [/^(\d+) products on current page$/, "$1 منتج في الصفحة الحالية"],
  [/^Subcategory of (.+)$/, "تصنيف فرعي من $1"],
  [/^(\d+) matching warehouses?$/, "$1 مستودع مطابق"],
  [/^(\d+) matching suppliers?$/, "$1 مورّد مطابق"],
  [/^(\d+) matching orders?$/, "$1 طلب مطابق"],
  [/^(\d+) matching customers?$/, "$1 عميل مطابق"],
  [/^(\d+) items?$/, "$1 بند"],
  [/^(\d+) lines?$/, "$1 بند"],
  [/^Supplier #(\d+)$/, "المورد رقم $1"],
];

export function translateArabicText(value) {
  const trimmed = value.trim();
  if (!trimmed) return value;
  const direct = arabicUi[trimmed];
  const translated =
    direct ||
    patterns.reduce(
      (result, [pattern, replacement]) =>
        result ||
        (pattern.test(trimmed) ? trimmed.replace(pattern, replacement) : ""),
      "",
    );
  return translated ? value.replace(trimmed, translated) : value;
}
