import { useDeferredValue, useEffect, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { AlertTriangle, Building2, ChevronLeft, ChevronRight, CircleDollarSign, Mail, MapPin, MoreHorizontal, Pencil, Phone, Plus, Search, Trash2, UserRound, UsersRound } from 'lucide-react'
import { toast } from 'sonner'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuTrigger } from '@/components/ui/dropdown-menu'
import { useAuth } from '@/features/auth/auth-provider'
import { hasPermission, PERMISSIONS } from '@/shared/permissions/permissions'
import { CustomerDialog } from './customer-dialog'
import { customersApi } from './api'

const PAGE_SIZE = 12
const money = (value) => new Intl.NumberFormat('en-JO', { style: 'currency', currency: 'JOD' }).format(Number(value || 0))

export function CustomersPage() {
  const { user } = useAuth(); const canManage = hasPermission(user, PERMISSIONS.CUSTOMERS_MANAGE); const client = useQueryClient()
  const [search, setSearch] = useState(''); const deferredSearch = useDeferredValue(search); const [status, setStatus] = useState('true'); const [city, setCity] = useState(''); const [page, setPage] = useState(1); const [editor, setEditor] = useState({ open: false, customer: null })
  const filters = { page, size: PAGE_SIZE, search: deferredSearch, status, city }
  const query = useQuery({ queryKey: ['customers', filters], queryFn: () => customersApi.list(filters) })
  const all = useQuery({ queryKey: ['customers-summary'], queryFn: () => customersApi.list({ page: 1, size: 1, status: '' }) })
  const active = useQuery({ queryKey: ['customers-summary-active'], queryFn: () => customersApi.list({ page: 1, size: 1, status: 'true' }) })
  const cities = useQuery({ queryKey: ['customer-cities'], queryFn: customersApi.cities })
  const customers = query.data?.items || []; const total = query.data?.total || 0; const pages = Math.max(1, Math.ceil(total / PAGE_SIZE))
  useEffect(() => setPage(1), [deferredSearch, status, city])
  const refresh = () => { client.invalidateQueries({ queryKey: ['customers'] }); client.invalidateQueries({ queryKey: ['customers-summary'] }); client.invalidateQueries({ queryKey: ['customer-cities'] }) }
  const save = useMutation({ mutationFn: (input) => editor.customer ? customersApi.update(editor.customer.id, input) : customersApi.create(input), onSuccess: () => { toast.success(editor.customer ? 'Customer updated successfully' : 'Customer added successfully'); setEditor({ open: false, customer: null }); refresh() }, onError: (error) => toast.error(error.message) })
  const deactivate = useMutation({ mutationFn: customersApi.deactivate, onSuccess: () => { toast.success('Customer deactivated'); refresh() }, onError: (error) => toast.error(error.message) })
  return <div className="customer-page">
    <section className="customer-hero"><div><p>Sales relationships</p><h1>Customer directory</h1><span>One reliable customer record for quotations, orders, invoices, and statements.</span></div><div className="customer-hero-art"><UsersRound /><span>CRM</span></div>{canManage && <Button size="lg" onClick={() => setEditor({ open: true, customer: null })}><Plus />Add customer</Button>}</section>
    <section className="customer-metrics"><Metric icon={UsersRound} label="Total customers" value={all.isLoading ? '—' : all.data?.total || 0} detail="Complete customer base" /><Metric icon={UserRound} label="Active customers" value={active.isLoading ? '—' : active.data?.total || 0} detail="Available for new sales" /><Metric icon={Building2} label="Covered cities" value={cities.isLoading ? '—' : cities.data?.length || 0} detail="Customer market reach" /><Metric icon={CircleDollarSign} label="Matching credit" value={query.isLoading ? '—' : money(customers.reduce((sum, item) => sum + Number(item.credit_limit), 0))} detail="Current page credit limits" /></section>
    <section className="customer-directory"><header><div><p>Customer master data</p><h2>Accounts and contacts</h2></div><span>{total} matching {total === 1 ? 'customer' : 'customers'}</span></header><div className="customer-toolbar"><div className="search-box"><Search /><Input placeholder="Search code, name, contact, phone, or tax number..." value={search} onChange={(event) => setSearch(event.target.value)} /></div><select className="form-select" value={city} onChange={(event) => setCity(event.target.value)}><option value="">All cities</option>{cities.data?.map((item) => <option key={item}>{item}</option>)}</select><select className="form-select" value={status} onChange={(event) => setStatus(event.target.value)}><option value="">All statuses</option><option value="true">Active customers</option><option value="false">Inactive customers</option></select></div>
      {query.isLoading ? <State><div className="loader" /><p>Loading customers...</p></State> : query.isError ? <State><AlertTriangle /><h3>Unable to load customers</h3><Button variant="outline" onClick={() => query.refetch()}>Try again</Button></State> : customers.length === 0 ? <State><UsersRound /><h3>No matching customers</h3><p>Add the first customer or change the current filters.</p>{canManage && <Button onClick={() => setEditor({ open: true, customer: null })}><Plus />Add first customer</Button>}</State> : <div className="customer-table-wrap"><table className="customer-table"><thead><tr><th>Customer</th><th>Primary contact</th><th>Location</th><th>Credit limit</th><th>Status</th><th /></tr></thead><tbody>{customers.map((customer) => <CustomerRow key={customer.id} customer={customer} canManage={canManage} onEdit={() => setEditor({ open: true, customer })} onDeactivate={() => { if (window.confirm(`Deactivate ${customer.name}? The record will remain available for historical transactions.`)) deactivate.mutate(customer.id) }} />)}</tbody></table></div>}
      {pages > 1 && <div className="supplier-pagination"><span>Page {page} of {pages}</span><div><Button variant="outline" size="sm" disabled={page === 1} onClick={() => setPage(page - 1)}><ChevronLeft />Previous</Button><Button variant="outline" size="sm" disabled={page >= pages} onClick={() => setPage(page + 1)}>Next<ChevronRight /></Button></div></div>}
    </section><CustomerDialog open={editor.open} onOpenChange={(open) => setEditor({ open, customer: open ? editor.customer : null })} customer={editor.customer} onSave={(input) => save.mutate(input)} loading={save.isPending} />
  </div>
}

function Metric({ icon: Icon, label, value, detail }) { return <article className="customer-metric"><span><Icon /></span><div><p>{label}</p><strong>{value}</strong><small>{detail}</small></div></article> }
function CustomerRow({ customer, canManage, onEdit, onDeactivate }) { return <tr className={customer.is_active ? '' : 'inactive-row'}><td><div className="customer-identity"><span>{customer.name.slice(0, 2).toUpperCase()}</span><div><strong>{customer.name}</strong><small>{customer.code}{customer.tax_number ? ` · ${customer.tax_number}` : ''}</small></div></div></td><td><div className="customer-contact-cell"><strong>{customer.contact_person || 'No contact assigned'}</strong><small>{customer.email ? <><Mail />{customer.email}</> : customer.phone ? <><Phone />{customer.phone}</> : 'No contact details'}</small></div></td><td><div className="customer-location"><MapPin /><span><strong>{customer.city || 'Not specified'}</strong><small>{customer.address || 'No address provided'}</small></span></div></td><td><strong>{money(customer.credit_limit)}</strong><small className="table-caption">Approved ceiling</small></td><td><span className={`status ${customer.is_active ? 'active' : 'inactive'}`}><i />{customer.is_active ? 'Active' : 'Inactive'}</span></td><td>{canManage && <DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon"><MoreHorizontal /></Button></DropdownMenuTrigger><DropdownMenuContent><DropdownMenuItem onSelect={onEdit}><Pencil />Edit customer</DropdownMenuItem>{customer.is_active && <><DropdownMenuSeparator /><DropdownMenuItem className="text-destructive" onSelect={onDeactivate}><Trash2 />Deactivate customer</DropdownMenuItem></>}</DropdownMenuContent></DropdownMenu>}</td></tr> }
function State({ children }) { return <div className="customer-state">{children}</div> }
